"""added color column to Subjects

Revision ID: 056b4705c0e2
Revises: 08e196e2a5bf
Create Date: 2020-03-08 07:57:17.825662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056b4705c0e2'
down_revision = '08e196e2a5bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('color', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subject', 'color')
    # ### end Alembic commands ###
