"""user subject many to many table fix

Revision ID: 08e196e2a5bf
Revises: e8c28695b135
Create Date: 2020-03-07 22:21:29.328915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08e196e2a5bf'
down_revision = 'e8c28695b135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersubjects',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'subject_id')
    )
    op.drop_table('subjects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name='subjects_subject_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='subjects_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'subject_id', name='subjects_pkey')
    )
    op.drop_table('usersubjects')
    # ### end Alembic commands ###
