"""user subjects key 1

Revision ID: 1571a6ab2ca4
Revises: 65f9eb560867
Create Date: 2020-05-03 23:09:26.268632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1571a6ab2ca4'
down_revision = '65f9eb560867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usersubjects', sa.Column('user_sub_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('usersubjects', 'user_subject_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usersubjects', sa.Column('user_subject_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('usersubjects', 'user_sub_id')
    # ### end Alembic commands ###
