"""subject description added

Revision ID: 16ba5ffcc5a3
Revises: a5fb8195fd15
Create Date: 2020-04-09 20:53:19.965662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16ba5ffcc5a3'
down_revision = 'a5fb8195fd15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usersubjects', sa.Column('subject_description', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usersubjects', 'subject_description')
    # ### end Alembic commands ###
