"""removed test columns

Revision ID: 5e2408aaa6f7
Revises: 52f17d88136a
Create Date: 2020-03-07 19:51:34.100231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e2408aaa6f7'
down_revision = '52f17d88136a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_gayness', table_name='user')
    op.drop_column('user', 'weight')
    op.drop_column('user', 'gayness')
    op.drop_column('user', 'sleepiness')
    op.drop_column('user', 'happiness')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('happiness', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('sleepiness', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('gayness', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_user_gayness', 'user', ['gayness'], unique=True)
    # ### end Alembic commands ###
