"""user subjects key

Revision ID: 65f9eb560867
Revises: 16ba5ffcc5a3
Create Date: 2020-05-03 22:58:24.088282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65f9eb560867'
down_revision = '16ba5ffcc5a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usersubjects', sa.Column('user_subject_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usersubjects', 'user_subject_id')
    # ### end Alembic commands ###
