"""user subjects key removed

Revision ID: b2d22d1a1c39
Revises: 1571a6ab2ca4
Create Date: 2020-05-03 23:12:19.191289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2d22d1a1c39'
down_revision = '1571a6ab2ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usersubjects', 'user_sub_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usersubjects', sa.Column('user_sub_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
