"""remove avatar from user

Revision ID: df9cf377c798
Revises: aaabb187d11e
Create Date: 2020-03-24 19:56:12.280031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df9cf377c798'
down_revision = 'aaabb187d11e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_url', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
