version: '3.7'

services: 

    gnosis:
        build: 
            context: ./gnosis
            dockerfile: Dockerfile
        volumes:
            - type: bind
              source: ./gnosis
              target: /home/gnosis/services/gnosis
        ports:
            - 8000:5000
        environment: 
            - FLASK_APP=home/gnosis/services/gnosis/gnosis.py

