version: '3.7'

services: 

    gnosis:
        build: 
            context: ./gnosis
            dockerfile: Dockerfile
        volumes:
            - type: bind
              source: ./gnosis
              target: /home/gnosis/services/gnosis
            - type: bind
              source: ./gnosis/local_config/.aws
              target: /home/gnosis/.aws
        ports:
            - 8080:5000
            - 5432:5432
            - 8000:8000
        environment: 
            - FLASK_APP=home/gnosis/services/gnosis/gnosis.py
 
