version: '3.7'

services: 

    gnosis:
        build: 
            context: ./gnosis
            dockerfile: Dockerfile
        volumes:
            - type: bind
              source: ./gnosis
              target: /home/gnosis/services/gnosis
        ports:
            - 8000:5000
        environment: 
            - FLASK_APP=home/gnosis/services/gnosis/gnosis.py
            - DATABASE_URL=postgresql://postgres:robertnields2020@cta-gnosis-db-dev.cd1wzcrr5t3s.us-east-1.rds.amazonaws.com

