version: '3.7'

services: 

    users:
        build: 
            context: ./users
            dockerfile: Dockerfile
        volumes:
            - type: bind
              source: ./users
              target: /home/gnosis/services/users
        ports:
            - 8000:5000
        environment: 
            - FLASK_APP=home/gnosis/services/users/gnosis.py
            - FLASK_ENV=development